add rate limiter
rarimo/horizon-svc pull request #2
Opened 2023-11-02 15:25 UTC by napalmpapalam

2023-11-02 15:34 UTC, ihordiachenko requested changes

2023-11-02 15:34 UTC, ihordiachenko commented on internal/config/rate_limiter.go
> +type RateLimiterConfig struct {
Add it to the config docs and examples

2023-11-03 08:43 UTC, napalmpapalam commented on internal/config/rate_limiter.go
> +type RateLimiterConfig struct {
👌

2023-11-03 15:35 UTC, ihordiachenko approved these changes

2023-11-06 06:38 UTC, merged